import { ChatChannelTypeHrid } from "src/MooLite/core/chat/ChatChannelTypeHrid";
import { ConversationMessage } from "src/MooLite/plugins/WhisperManager/ConversationMessage";

export const contributorNames: string[] = ["LagunaE", "Sleutelkind"];
export const betaTesterNames: string[] = ["JBQ", "knighterd", "Thessaloniki", "Houston"];
export const helperNames: string[] = ["Champ", "ML", "Maxion", "hoador"];

export const conversationData: Record<string, ConversationMessage[]> = {
    Zeplin: [
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Hey, how's it going?",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Zeplin",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Zeplin",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
    ],
    Squall: [
        {
            senderName: "Squall",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Hey, how's it going?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Squall",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Squall",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
    ],
    Rinoa: [
        {
            senderName: "Rinoa",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Hey, how's it going?",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Laguna",
            receiverName: "Rinoa",
            channel: ChatChannelTypeHrid.Whisper,
            message: "Pretty good, you?",
            isInbound: false,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
        {
            senderName: "Rinoa",
            receiverName: "Laguna",
            channel: ChatChannelTypeHrid.Whisper,
            message: "I'm doing well, thanks for asking!",
            isInbound: true,
            isDeleted: false,
            isModMessage: false,
            isSystemMessage: false,
        },
    ],
};
