export enum SkillHrid {
 Attack = "/skills/attack",
 Brewing = "/skills/brewing",
 CheeseSmithing = "/skills/cheesesmithing",
 Cooking = "/skills/cooking",
 Crafting = "/skills/crafting",
 Defense = "/skills/defense",
 Enhancing = "/skills/enhancing",
 Foraging = "/skills/foraging",
 Intelligence = "/skills/intelligence",
 Magic = "/skills/magic",
 Milking = "/skills/milking",
 Power = "/skills/power",
 Ranged = "/skills/ranged",
 Stamina = "/skills/stamina",
 Tailoring = "/skills/tailoring",
 Woodcutting = "/skills/woodcutting",
}
