name: CI
on: push
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Prettier
        run: npm run lint:check
#      - name: Run tests
#        run: npm run test
      - name: Build
        run: npm run build
